### ISSUE TITLE
Fill out information in README.md

### ISSUE THREAD

**Issue by avahoffman** [fhdsl/GDSCN_BioDIGS_Book#30]

**Comment by ehumph** [comment]
Done! Forgot to link to the PR

**Comment by avahoffman** [comment]
@ehumph you can link after the fact with # plus the PR number. 

The refs still look a bit wonky and you'll have to replace the Rmd with md syntax here:

![image](https://github.com/user-attachments/assets/9d0f1e61-280f-4f29-81c7-099b7d407af0)

**Comment by ehumph** [comment]
@avahoffman Hopefully this is right now. (I removed the paragraph with the citations because it just seemed like too many words for a brief overview.)

**Comment by avahoffman** [comment]
Awesome! 

Resolved by #32
